/* data.js */
const PROJECT_DATA = {
    personal: [
        { project: "Stones", id: "Stones-4656", src: "images/personal/Personal_Stones-4656.jpg", cap: "Stones-001" },
        { project: "Stones", id: "Stones-4658", src: "images/personal/Personal_Stones-4658.jpg", cap: "Stones-002" },
        { project: "Goto Islands", id: "Goto-3", src: "images/personal/Goto-Islands-3.jpg", cap: "Goto Islands-001" },
        { project: "Goto Islands", id: "Goto-9", src: "images/personal/Goto-Islands-9.jpg", cap: "Goto Islands-002" },
        { project: "Goto Islands", id: "Goto-21", src: "images/personal/Goto-Islands-21.jpg", cap: "Goto Islands-003" },
        { project: "Goto Islands", id: "Goto-31", src: "images/personal/Goto-Islands-31.jpg", cap: "Goto Islands-004" },
        { project: "Goto Islands", id: "Goto-32", src: "images/personal/Goto-Islands-32.jpg", cap: "Goto Islands-005" },
        { project: "Goto Islands", id: "Goto-35", src: "images/personal/Goto-Islands-35.jpg", cap: "Goto Islands-006" },
        { project: "Goto Islands", id: "Goto-41", src: "images/personal/Goto-Islands-41.jpg", cap: "Goto Islands-007" },
        { project: "Goto Islands", id: "Goto-61", src: "images/personal/Goto-Islands-61.jpg", cap: "Goto Islands-008" },
        { project: "Goto Islands", id: "Goto-65", src: "images/personal/Goto-Islands-65.jpg", cap: "Goto Islands-009" },
        { project: "Goto Islands", id: "Goto-72", src: "images/personal/Goto-Islands-72.jpg", cap: "Goto Islands-010" },
        { project: "Goto Islands", id: "Goto-80", src: "images/personal/Goto-Islands-80.jpg", cap: "Goto Islands-011" },
        { project: "Goto Islands", id: "Goto-85", src: "images/personal/Goto-Islands-85.jpg", cap: "Goto Islands-012" },
        { project: "Goto Islands", id: "Goto-95", src: "images/personal/Goto-Islands-95.jpg", cap: "Goto Islands-013" },
        { project: "Goto Islands", id: "Goto-102", src: "images/personal/Goto-Islands-102.jpg", cap: "Goto Islands-014" },
        { project: "Goto Islands", id: "Goto-108", src: "images/personal/Goto-Islands-108.jpg", cap: "Goto Islands-015" },
        { project: "Goto Islands", id: "Goto-121", src: "images/personal/Goto-Islands-121.jpg", cap: "Goto Islands-016" },
        { project: "Goto Islands", id: "Goto-122", src: "images/personal/Goto-Islands-122.jpg", cap: "Goto Islands-017" },
        { project: "Landscape, Asia", id: "srilanka-3397", src: "images/personal/Personal_SriLanka-3397.jpg", cap: "Landscape, Asia-001" },
        { project: "Landscape, Asia", id: "srilanka-2876", src: "images/personal/Personal_SriLanka-2876.jpg", cap: "Landscape, Asia-002" },
        { project: "Landscape, Asia", id: "srilanka-2883", src: "images/personal/Personal_SriLanka-2883.jpg", cap: "Landscape, Asia-003" },
        { project: "Landscape, Asia", id: "srilanka-2892", src: "images/personal/Personal_SriLanka-2892.jpg", cap: "Landscape, Asia-004" },
        { project: "Landscape, Asia", id: "srilanka-2901", src: "images/personal/Personal_SriLanka-2901.jpg", cap: "Landscape, Asia-005" },
        { project: "Landscape, Asia", id: "srilanka-2912", src: "images/personal/Personal_SriLanka-2912.jpg", cap: "Landscape, Asia-006" },
        { project: "Landscape, Asia", id: "srilanka-2933", src: "images/personal/Personal_SriLanka-2933.jpg", cap: "Landscape, Asia-007" },
        { project: "Landscape, Asia", id: "srilanka-3060", src: "images/personal/Personal_SriLanka-3060.jpg", cap: "Landscape, Asia-008" },
        { project: "Landscape, Asia", id: "srilanka-3086", src: "images/personal/Personal_SriLanka-3086.jpg", cap: "Landscape, Asia-009" },
        { project: "Landscape, Asia", id: "srilanka-3108", src: "images/personal/Personal_SriLanka-3108.jpg", cap: "Landscape, Asia-010" },
        { project: "Landscape, Asia", id: "srilanka-3226", src: "images/personal/Personal_SriLanka-3226.jpg", cap: "Landscape, Asia-011" },
        { project: "Landscape, Asia", id: "srilanka-3386", src: "images/personal/Personal_SriLanka-3386.jpg", cap: "Landscape, Asia-012" },
        { project: "Landscape, Asia", id: "srilanka-3345", src: "images/personal/Personal_SriLanka-3345.jpg", cap: "Landscape, Asia-013" },
        { project: "Landscape, Europe", id: "germany-4667", src: "images/personal/Germany-4667.jpg", cap: "Architecture, Europe-001" },
        { project: "Landscape, Europe", id: "germany-4686", src: "images/personal/Germany-4686.jpg", cap: "Architecture, Europe-002" },
        { project: "Landscape, Europe", id: "germany-4699", src: "images/personal/Germany-4699.jpg", cap: "Architecture, Europe-003" },
        { project: "Landscape, Europe", id: "germany-4309", src: "images/personal/UK-4309-002.jpg", cap: "Architecture, Europe-004" },
        { project: "Landscape, Europe", id: "germany-4331", src: "images/personal/UK-4331-004.jpg", cap: "Architecture, Europe-005" },
        { project: "Landscape, Europe", id: "germany-4333", src: "images/personal/UK-4333-005.jpg", cap: "Architecture, Europe-006" },
        { project: "Landscape, Europe", id: "germany-4342", src: "images/personal/UK-4342-006.jpg", cap: "Architecture, Europe-007" },
        { project: "Landscape, Europe", id: "germany-4357", src: "images/personal/UK-4357-007.jpg", cap: "Architecture, Europe-008" },
        { project: "Landscape, Europe", id: "germany-4653", src: "images/personal/Germany-4653.jpg", cap: "Landscape, Europe-001" },
        { project: "Landscape, Europe", id: "UK-4389", src: "images/personal/UK-4389.jpg", cap: "Landscape, Europe-002" },
        { project: "Landscape, Europe", id: "UK-4409", src: "images/personal/UK-4409.jpg", cap: "Landscape, Europe-003" },
        { project: "Landscape, Europe", id: "UK-4416", src: "images/personal/UK-4416.jpg", cap: "Landscape, Europe-004" },
        { project: "Landscape, Europe", id: "UK-4419", src: "images/personal/UK-4419.jpg", cap: "Landscape, Europe-005" },
        { project: "Landscape, Europe", id: "UK-4465", src: "images/personal/UK-4465.jpg", cap: "Landscape, Europe-006" },
        { project: "Landscape, Europe", id: "UK-4384", src: "images/personal/UK-4384.jpg", cap: "Landscape, Europe-007" },
        { project: "Landscape, Europe", id: "UK-4397", src: "images/personal/UK-4397.jpg", cap: "Landscape, Europe-008" },
        { project: "Landscape, Europe", id: "UK-4439", src: "images/personal/UK-4439.jpg", cap: "Landscape, Europe-009" },
        { project: "Landscape, Europe", id: "UK-4490", src: "images/personal/UK-4490.jpg", cap: "Landscape, Europe-010" },
        { project: "Landscape, Europe", id: "UK-4386", src: "images/personal/UK-4386-008.jpg", cap: "Landscape, Europe-011" },
        { project: "Landscape, Japan", id: "Kamikouchi-0005", src: "images/personal/Kamikouchi-0005-020.jpg", cap: "Landscape, Japan-001" },
        { project: "Landscape, Japan", id: "Kamikouchi-0013", src: "images/personal/Kamikouchi-0013-021.jpg", cap: "Landscape, Japan-002" },
        { project: "Landscape, Japan", id: "Kamikouchi-9583", src: "images/personal/Kamikouchi-9583-003.jpg", cap: "Landscape, Japan-003" },
        { project: "Landscape, Japan", id: "Kamikouchi-9656", src: "images/personal/Kamikouchi-9656-005.jpg", cap: "Landscape, Japan-004" },
        { project: "Landscape, Japan", id: "Kamikouchi-9675", src: "images/personal/Kamikouchi-9675-009.jpg", cap: "Landscape, Japan-005" },
        { project: "Landscape, Japan", id: "Kamikouchi-9713", src: "images/personal/Kamikouchi-9713-014.jpg", cap: "Landscape, Japan-006" },
        { project: "Landscape, Japan", id: "Kamikouchi-4789", src: "images/personal/Kirigamine-4789-004.jpg", cap: "Landscape, Japan-007" },
        { project: "Landscape, Japan", id: "Kamikouchi-4830", src: "images/personal/Kirigamine-4830-006.jpg", cap: "Landscape, Japan-008" },
        { project: "Dessau", id: "Dessau-11", src: "images/personal/trip-to-europe-11.jpg", cap: "Dessau-001" },
        { project: "Dessau", id: "Dessau-13", src: "images/personal/trip-to-europe-13.jpg", cap: "Dessau-002" },
        { project: "Dessau", id: "Dessau-14", src: "images/personal/trip-to-europe-14.jpg", cap: "Dessau-003" },
        { project: "Dessau", id: "Dessau-16", src: "images/personal/trip-to-europe-16.jpg", cap: "Dessau-004" },
        { project: "Dessau", id: "Dessau-19", src: "images/personal/trip-to-europe-19.jpg", cap: "Dessau-005" }
    ],
    commissioned: [
        { project: "Tentative, Echoes", id: "Echoes_Eye", src: "images/commissioned/Echoes_Eye.jpg", cap: "Vol.1 Eye" },
        { project: "Tentative, Echoes", id: "Echoes_Ear-2", src: "images/commissioned/Echoes_Ear-2.jpg", cap: "Vol.1 Ear" },   
        { project: "Popeye Web, Japanese Breakfast", id: "Popeye_JB_001", src: "images/commissioned/Popeye_JapaneseBreakfast-0327.jpg", cap: "Japanese Breakfast-001" },
        { project: "Popeye Web, Japanese Breakfast", id: "Popeye_JB_002", src: "images/commissioned/Popeye_JapaneseBreakfast-0431.jpg", cap: "Japanese Breakfast-002" },
        { project: "Popeye Web, Japanese Breakfast", id: "Popeye_JB_003", src: "images/commissioned/Popeye_JapaneseBreakfast-0468.jpg", cap: "Japanese Breakfast-003" },
        { project: "Popeye Web, Japanese Breakfast", id: "Popeye_JB_004", src: "images/commissioned/Popeye_JapaneseBreakfast-0436.jpg", cap: "Japanese Breakfast-004" },
        { project: "Popeye Web, Japanese Breakfast", id: "Popeye_JB_005", src: "images/commissioned/Popeye_JapaneseBreakfast-0456.jpg", cap: "Japanese Breakfast-005" },
        { project: "OAO 2026 Spring-Summer Preview", id: "OAO_001", src: "images/commissioned/OAO-Exhibition-4310.jpg", cap: "OAO 2026 Spring/Summer Preview-001" },
        { project: "OAO 2026 Spring-Summer Preview", id: "OAO_002", src: "images/commissioned/OAO-Exhibition-4343.jpg", cap: "OAO 2026 Spring/Summer Preview-002" },
        { project: "OAO 2026 Spring-Summer Preview", id: "OAO_003", src: "images/commissioned/OAO-Exhibition-4398.jpg", cap: "OAO 2026 Spring/Summer Preview-003" },
        { project: "OAO 2026 Spring-Summer Preview", id: "OAO_004", src: "images/commissioned/OAO-Exhibition-4413.jpg", cap: "OAO 2026 Spring/Summer Preview-004" },
        { project: "OAO 2026 Spring-Summer Preview", id: "OAO_005", src: "images/commissioned/OAO-Exhibition-4421.jpg", cap: "OAO 2026 Spring/Summer Preview-005" },
        { project: "OAO 2026 Spring-Summer Preview", id: "OAO_006", src: "images/commissioned/OAO-Exhibition-4480.jpg", cap: "OAO 2026 Spring/Summer Preview-006" },
        { project: "OAO 2026 Spring-Summer Preview", id: "OAO_007", src: "images/commissioned/OAO-Exhibition-4509.jpg", cap: "OAO 2026 Spring/Summer Preview-007" },
        { project: "OAO 2026 Spring-Summer Preview", id: "OAO_008", src: "images/commissioned/OAO-Exhibition-4538.jpg", cap: "OAO 2026 Spring/Summer Preview-008" },
        { project: "Kan Izumi, New Balance Gray Days", id: "Kan Izumi New Balance Grays-0172", src: "images/commissioned/NewBalance-GrayDays_DSCF0172.jpg", cap: "Kan Izumi, New Balance Gray Days-001" },
        { project: "Kan Izumi, New Balance Gray Days", id: "Kan Izumi New Balance Grays-0224", src: "images/commissioned/NewBalance-GrayDays_DSCF0224.jpg", cap: "Kan Izumi, New Balance Gray Days-002" },
        { project: "Kan Izumi, New Balance Gray Days", id: "Kan Izumi New Balance Grays-0230", src: "images/commissioned/NewBalance-GrayDays_DSCF0230.jpg", cap: "Kan Izumi, New Balance Gray Days-003" },
        { project: "Kan Izumi, New Balance Gray Days", id: "Kan Izumi New Balance Grays-0235", src: "images/commissioned/NewBalance-GrayDays_DSCF0235.jpg", cap: "Kan Izumi, New Balance Gray Days-004" },
        { project: "Perfume Oil Factory", id: "POF-1", src: "images/commissioned/POF-1.jpg", cap: "Perfume Oil Factory-001" },
        { project: "Perfume Oil Factory", id: "POF-2", src: "images/commissioned/POF-2.jpg", cap: "Perfume Oil Factory-002" },
        { project: "Perfume Oil Factory", id: "POF-3", src: "images/commissioned/POF-3.jpg", cap: "Perfume Oil Factory-003" },
        { project: "Perfume Oil Factory", id: "POF-4", src: "images/commissioned/POF-4.jpg", cap: "Perfume Oil Factory-004" },
        { project: "Perfume Oil Factory", id: "POF-5", src: "images/commissioned/POF-5.jpg", cap: "Perfume Oil Factory-005" },
        { project: "Igusa Farmer", id: "IF-1", src: "images/commissioned/Igusa Farmer-2106.jpg", cap: "Igusa Farmer for Satsuki Ueda-001" },
        { project: "Igusa Farmer", id: "IF-2", src: "images/commissioned/Igusa Farmer-2131.jpg", cap: "Igusa Farmer for Satsuki Ueda-002" },
        { project: "Igusa Farmer", id: "IF-3", src: "images/commissioned/Igusa Farmer-2162.jpg", cap: "Igusa Farmer for Satsuki Ueda-003" },
        { project: "Igusa Farmer", id: "IF-4", src: "images/commissioned/Igusa Farmer-2332.jpg", cap: "Igusa Farmer for Satsuki Ueda-004" },
        { project: "Igusa Farmer", id: "IF-5", src: "images/commissioned/Igusa Farmer-2387.jpg", cap: "Igusa Farmer for Satsuki Ueda-005" },
        { project: "Igusa Farmer", id: "IF-6", src: "images/commissioned/Igusa Farmer-2442.jpg", cap: "Igusa Farmer for Satsuki Ueda-006" },
        { project: "Igusa Farmer", id: "IF-7", src: "images/commissioned/Igusa Farmer-2466.jpg", cap: "Igusa Farmer for Satsuki Ueda-007" },
        { project: "Igusa Farmer", id: "IF-8", src: "images/commissioned/Igusa Farmer-2506.jpg", cap: "Igusa Farmer for Satsuki Ueda-008" },
        { project: "Igusa Farmer", id: "IF-9", src: "images/commissioned/Igusa Farmer-5999.jpg", cap: "Igusa Farmer for Satsuki Ueda-009" },
        { project: "Igusa Farmer", id: "IF-10", src: "images/commissioned/Igusa Farmer-6081.jpg", cap: "Igusa Farmer for Satsuki Ueda-010" },
        { project: "Igusa Farmer", id: "IF-11", src: "images/commissioned/Igusa Farmer-6105.jpg", cap: "Igusa Farmer for Satsuki Ueda-011" },
        { project: "Igusa Farmer", id: "IF-12", src: "images/commissioned/Igusa Farmer-6141.jpg", cap: "Igusa Farmer for Satsuki Ueda-012" },
        { project: "Igusa Farmer", id: "IF-13", src: "images/commissioned/Igusa Farmer-6150.jpg", cap: "Igusa Farmer for Satsuki Ueda-013" }
    ]
};